# Generated by Django 4.1.7 on 2023-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
