# Generated by Django 4.1.7 on 2023-02-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0002_voiture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
