# Generated by Django 4.1.7 on 2023-02-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0004_alter_voiture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='propriete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applic.propriete'),
        ),
    ]
