# Generated by Django 4.1.5 on 2023-02-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0005_voiture_propriete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_fabrication', models.IntegerField()),
                ('couleur', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
    ]
