# Generated by Django 4.2 on 2023-04-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applic', '0006_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
